### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by firefly-cpp**
- new test,
- FA moved to the class,
- README.rst removed,
- updated example in README

### CODE REVIEW

**Comment by firefly-cpp** [comment]
@zStupan, I can not assign you a reviewer role for this PR.

**Comment by zStupan** [comment]
@firefly-cpp I think I have to be added as a collaborator for that, I'm not sure though.

As for the review, I'd rename `move()` to `run()`, move the func, dim, lb, ub and max_evals parameters to run and have the rng as an attribute of the class. Something like this:

```python
import numpy as np
from numpy.random import default_rng


class FireflyAlgorithm:
    def __init__(self, pop_size=20, alpha=1.0, betamin=1.0, gamma=0.01, seed=None):
        self.pop_size = pop_size
        self.alpha = alpha
        self.betamin = betamin
        self.gamma = gamma
        self.rng = default_rng(seed)
    
    def run(self, function, dim, lb, ub, max_evals):
        fireflies = self.rng.uniform(lb, ub, (self.pop_size, dim))
        intensity = np.apply_along_axis(function, 1, fireflies)
        best = np.min(intensity)

        evaluations = self.pop_size
        new_alpha = self.alpha
        search_range = ub - lb

        while evaluations <= self.max_evals:
            new_alpha *= 0.97
            for i in range(self.pop_size):
                for j in range(self.pop_size):
                    if intensity[i] >= intensity[j]:
                        r = np.sum(np.square(fireflies[i] - fireflies[j]), axis=-1)
                        beta = self.betamin * np.exp(-self.gamma * r)
                        steps = new_alpha * (self.rng.random(self.dim) - 0.5) * search_range
                        fireflies[i] += beta * (fireflies[j] - fireflies[i]) + steps
                        fireflies[i] = np.clip(fireflies[i], lb, ub)
                        intensity[i] = function(fireflies[i])
                        evaluations += 1
                        best = min(intensity[i], best)
        return best
```

**Comment by firefly-cpp** [comment]
@zStupan, I thought you are already in this group. 

Let's try now.

**Comment by firefly-cpp** [comment]
Try to merge this PR (when you confirm).

**Review by zStupan — COMMENTED** [review]
Like I've said in the other comment, I'd change the class interface slightly, but everything else looks good.

**Pull request merged**
